### ISSUE TITLE
OBJ files search order is not the same as Propeller Tool

### ISSUE THREAD

**Issue by jacgoudsmit** [parallaxinc/OpenSpin#38]
I have a few large projects that I developed with the old Propeller Tool. When I tried compiling some of them with PropellerIDE (latest version from Github), I got some weird errors.

As it turns out, I had named one of my modules "clock.spin" and there is already such a module in the Spin libraries that are included with PropellerIDE. Both BSTC and the OpenSpin compiler found that library module before they found my module, so I got a weird error because it didn't recognize a subroutine name.

Obviously the workaround is to rename the module or put "." at the top of the include path, so it's a minor problem (though the weird error message didn't give any hints about why the subroutine name was wrong, which made it a major problem for me). But this has the potential of breaking user code in the future: Imagine a user has a module XYZZY.spin and then the team that works on the Spin libraries decides to introduce a module with the same name. As soon as the user installs the latest PropellerIDE, their existing source code stops working with no clear explanation, because the XYZZY.spin that the compiler now finds, is the one in the libraries, instead of the one that the user wrote.

The fix is to let the compiler look for modules mentioned in the OBJ section in the current directory first, before it searches in the include paths. This is how Propeller Tool worked, too. The chance that this would break existing code is minimal.

Sorry if this problem has already been addressed. I'm aware that PropellerIDE may not have the latest OpenSpin compiler.

**Comment by reltham** [comment]
Was PropellerIDE even using OpenSpin?  I think it defaults to use BSTC? Or at least did.

In any case, OpenSpin does already try the current working folder first for any files it loads, then it goes through the passed in paths.  Perhaps PropellerIDE is not setting the current working folder to match the path where the top object is compiled from?

So this is not an OpenSpin issue, it's a PropellerIDE issue.

**Comment by jacgoudsmit** [comment]
Thanks Roy. I'll look into it a little further.

**Comment by dbetz** [comment]
Doesn't PropellerIDE use it's own custom version of OpenSpin?

**Comment by reltham** [comment]
It does use it's own version, but it's not different in this respect as far as I know.

It's also no longer current with recent fixes to OpenSpin.  I told them not to do what they did, but they did it anyway.

**Comment by dbetz** [comment]
What did he change in OpenSpin? I wonder how hard it would be to modify PropellerIDE to use the standard version?

**Comment by reltham** [comment]
His version of OpenSpin has an alternate "openspin.cpp" wrapper file that uses a bunch of QT things instead of the generic code I have (like for parsing the command line, etc.) I think all that's really different is how it prints errors? Not really sure of the specifics.  Seems like it should be possible to fix PropellerIDE to use the real version of OpenSpin without his changes. He already has stuff in there to handle calling bstc, which he could not change.

Anyway, it's up to you guys, I never use PropellerIDE, also it seems abandoned now.  I still use PropTool mostly, and then command line to compile with OpenSpin if needed. 

I am on the verge of making my own PropTool like thing that uses OpenSpin... all these IDEs end up being more cumbersome than they need to be, everyone just wants PropTool (except cross platform and using OpenSpin).

**Comment by drawkula** [comment]
> everyone just wants PropTool (except cross platform and using OpenSpin).

Some projects got depending on BST's optimisations. :-(
Not a good idea but fact.
And some Windows users in my surrounding prefer BST's GUI just because of the code folding.
So much about my neighbours.

I prefer CUI/CLI stuff for coding.

**Comment by reltham** [comment]
Aside from the @@@, what does BSTC do that can't work in OpenSpin?  I have the unused method stuff, and it's more aggressive than BSTC's in most cases.  Everything else it does in "optimizations" are just in bytecode generation things, that should not matter really (unless you really do rely on the performance difference of a few clock cycles because of different bytecode generation).

**Comment by drawkula** [comment]
TriOS (the OS of [the Hive retro style DIY computer](https://hive-project.de/)) uses code that triggers [OpenSpin's limit of 256 subroutines + objects](https://github.com/parallaxinc/OpenSpin/issues/34) while it compiles with BSTC.

◁mean mode▷
I hope BST will stop to work on current OSes soon (too old LibC, too old syscall API, ...) so that a TriOS rewrite of this part becomes unavoidable. So I'm praying for the next Windows release becoming incompatible with BST! >:-)
◁/mean mode▷

**Comment by drawkula** [comment]
The design of TriOS just ran into that trap and is kind of locked in now. Every program which runs on TriOS depends on that file with the OS interface.
Splitting it is the way to go because all of the syscalls are needed somewhen by some programs. The file making the problems is the interface to the remote syscalls by translating them from a call to a PUB to some communication on the bus (call number and arguments). Sure that can be split in stuff like stdlib, fileio, graphics calls, ... and so on. But to get the whole Hive drones moving, I see no other way than to pray for BSTC getting incompatible with newer OSes... :-(

Ok. I just wanted to repeat that in the context of ...

> everyone just wants PropTool (except cross platform and using OpenSpin).

... to show that there are "other everyones" too.

This is a WontFix issue and that's ok.

But please think about putting code folding on the whishlist for "Roy's IDE".
I know some users which really love it. :-)

**Comment by bweir** [comment]
Alright, I need to jump in here.

I forked OpenSpin because Roy Eltham refused to accept a single qmake
project file in the mainline that would allow me to build it with Qt's
build system.

Now, since I already had the fork, I later decided to replace the command
line interface with one that would work with GNU help2man, and with a
different compliment of options. Looking back, the extra stuff was
unnecessary, and made it more work to keep up with the mainline.

Now, I knew back then that forking was a bad idea. I also think just using
the mainline version is the best way forward.

Here's the thing, and I said this then, and I'll say it again:

PropellerIDE can't use the mainline OpenSpin without a qmake project file.

For anyone who missed that:

PropellerIDE, a Qt project, built with qmake, needs a qmake project file to
build OpenSpin.

I asked for this change *four years ago*.

I'll say this again too:

It would NOT introduce a Qt dependency.

For awhile, I had the project file in the IDE project, but then I started
building the IDE with packthing, which means openspin wasn't so tightly
coupled to the IDE anymore, and the project file had to be with openspin.
Since my changes were not being merged in, I had no choice but to fork.

In any case, the qmake project file BELONGS in the OpenSpin project. Like
any other highly portable project, it should have a directory with build
files for different build systems, and why not? It has a makefile, and it
has a visual studio project file. Why not qmake? Or cmake? Or scons? Or
codeblocks? Or automake? Cocos2D does it, and it runs everywhere. If it can
build with qmake, it can run anywhere Qt runs, and deployed using all the
same tooling. I had automated builds set up for 4 platforms at one time,
and had been planning for mobile support too. I couldn't be messing around
with a makefile for every new environment. That would be make-work, no pun
intended.

A compromise could have been automating binary builds which I can then
consume, but Roy refused to ever work with me directly to coordinate our
efforts or find a solution to this problem, so here's where we are.

It wouldn't have been so bad either if it was some other trivial component,
but it was the *Spin compiler*. I needed that to make a *Spin IDE*. I
couldn't just wait around hoping for something to happen, because as you
can see, I'm still waiting for it.

I still have the email where he said he preferred to have a "single point
of contact" with Parallax, despite the fact that I'm not a Parallax
employee.

In the entire time I worked on this project, Roy refused to work with me
even a little bit, and this is the result.

Anyway, that's why I forked it, and I hated it then, and I hate it now.

And no. It would not be hard to use the mainline. All I need is that one
change. I can't believe this is still an issue.

**Comment by reltham** [comment]
You keep insisting that you need a qmake file added so you can build openspin as part of your whole build. This is simply not true.  You clearly didn't even try, because doing a search now shows ways to do it dating back to 2011.

Your fork now needs Qt stuff because you added a bunch of Qt stuff to your version of things.  If you just execute the normal make from your qmake (which you can do), then you can just build the exact source that's in the OpenSpin repository.

Let's not even get started on the license issues your fork causes, other than to say, since OpenSpin is MIT licensed, your introduction of Qt stuff to it throws GPL into the mix, and makes things a mess there.

Your existing stuff managed to talk to bstc without needing changes, so it can talk to OpenSpin without changes. 

TeamCity builds OpenSpin via the make files for all the same platforms you covered, so you would not need to make any make files.

So, back at you, I can't believe this is still an issue, that you could have resolved yourself years ago if you just looked. 

Also, I refused to help you, because it was your way or not at all, seems like it still is.

**Comment by bweir** [comment]
Starting at the top:

Saying that I didn't even try is simply not true. I spent months trying to
figure out how to package all the different pieces of PropellerIDE in a
repeatable, maintainable way. Openspin was just one piece. I'm not gonna
say every decision I made was right. It's possible I overlooked something.
But if it was really that easy, surely, you could have pointed me in a
better direction back then.

I already stated that I'd happily throw out all the Qt-specific stuff, that
it doesn't matter anymore, that I hated forking it in the first place.

Licensing? If that was really your concern, this shouldn't be the first
time you're mentioning that, and in any case, I'm familiar with Qt's
licensing model.

First off, Qt != qmake project file.

A qmake project file is literally a config file. Even if the binary does
get linked to Qt, the GPL only applies to the binary Qt blob, not openspin,
so that point is moot.

You're right though. My existing stuff does talk to bstc. After I wrote the
packaging tool to deal with it, after I wrote the connector to pull in
standalone binaries, since bstc was already a binary, and I reached out to
the creator and he wasn't willing to open the source, I had no choice. In
fact, on my epic todo list, adding a connector to drive makefiles to
packthing was on it, somewhere. I just never got around to it. So, yeah,
it's possible. Anything is possible. But when I'm hemorrhaging cash and the
only reason to do all that is because the project maintainer won't throw
you a bone, it takes a backseat to other things.

TeamCity was not building openspin way back when. If that's there now, then
none of this really matters. Mostly my frustration is on principle anyway,
that adding a qmake project file should never have been controversial in
the first place.

Everyone in the Spin community, please, correct me if I'm wrong, but I've
always felt that I was open to feedback, and did everything I could to do
the most good for the most people. I had hard choices to make along the
way, and the customer that I was focused on--kids, students--didn't always
have the same needs that the forum users did. I got a lot of flak from
different people when I added theme support to the IDE, but that feature
was extremely popular among the kids in the classes I worked with, so it
was absolutely worth it to me.

Really, you're right, in a sense. There were other ways around this
problem. At the time, I made one choice to solve it, and it allowed me to
move forward. If I had to do it again, I might do things differently today.
It just always felt like a missed opportunity to me that we never worked
together. I really wish we had.
