### ISSUE TITLE
Intent of DEV block designator?

### ISSUE THREAD

**Issue by avsa242** [parallaxinc/OpenSpin#41]
When I created a method with 'dev' as a parameter, openspin failed to build, stating "error : Block designator must be in first column"
At first I thought I accidentally indented the method's PUB block designator, but it wasn't, and after paying closer attention to the error, I noticed it marked the offending item as 'dev'
I was puzzled, looking through my source, but then thought maybe it was something in openspin I wasn't aware of, so grepping found it defined as a block designator in PropellerCompiler/PropellerCompiler.cpp
I didn't see it mentioned in the README, so wasn't sure what it was?
It's not a showstopper for me - I have little issue with changing the name of my variable, but thought I'd raise the issue in case someone else encountered it.

**Comment by reltham** [comment]
The DEV block was something in Chip's original compiler. I believe it was used during the development of the compiler.  The DEV block allows you to specify filenames as either pre (for pre-compiled) or arc (for archive) types, and it sticks them into an array inside the structure that PropTool & Chip's PNut tool use to communicate with the compiler core. I assume at one time Chip used them as he was developing the compiler with Jeff Martin. It was never documented by Parallax, as far as I know.  OpenSpin has it because it's a direct port of Chip's x86 compiler core code.

**Comment by PropGit** [comment]
Thanks @reltham 

Yes, this was functionality the the compiler implemented but that we never exposed to the user.  It was actually created sometime right before or right after initial public release of the Propeller Tool but was a backburner thing that never had code to support it in the IDE nor documentation written for it.  

The PRE files were intended to be automatically compiled as part of the current compilation process and who's resulting binary image was to be included as data in the current compilation.  Intended for the rare case where your current application needs the result of another application compilation to fully function, but without the need for two developer operations to make that happen.

The ARC files are simply references to project-related files that should be logically included in the project but don't necessarily have any code involved.  For example, there could be an executable or a PDF or some other project-related resource that's not necessarily an intrinsic part of the application itself, and ARC references it so that File > Archive operations include that file into the resulting zip file (for archival and sharing).

Come to think of it, PRE may have also been intended to run an executable which may generate a file which is later referenced by the FILE directive.  I can't remember for sure, but this sounds right.

None of this functionality had supporting processes in the IDE, so it went undocumented and unused, but the compiler supports it so it's functionality that could still be added high-level.

**Comment by avsa242** [comment]
I'm hoping it was okay to close this. It's several years old now and I believe OpenSpin is no longer maintained.
